[versions]
# libraries
junit = "4.13.2"
mockito = "4.11.0"
opentest4j = "1.3.0"
sentry = "8.13.2"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
kotlin = "2.3.0"
kover = "0.9.5"
qodana = "2025.3.1"
ktlint = "14.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
sentry = { group = "io.sentry", name = "sentry", version.ref = "sentry" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
